ALTER TABLE "Group"
ADD COLUMN     "destination" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "startDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "endDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "tripType" TEXT NOT NULL DEFAULT 'Other',
ADD COLUMN     "coverImage" TEXT;
